### ISSUE TITLE
Architecture globale

### ISSUE THREAD

**Issue by Liliaze** [Liliaze/N-PUZZLE#1]
Se mettre d'accord sur les données du projet, les lister.

**Comment by mdugot42** [comment]
Creation des classes Main, Solver, Node et State
Main : fichier a lancer au démarrage
Solver : contient les principales fonctions (algo, heuristique, parser...) et les listes 'opened' et 'closed'
State : permet de stocker une grille du puzzle et les méthodes en relation. 
Node : utilisé dans les listes opened/closed. Contient une grille sous la forme d'un objet State plus une liste chainée de toutes les étapes précédent cette grille.
