### ISSUE TITLE
Choix heuristiques

### ISSUE THREAD

**Issue by Liliaze** [Liliaze/N-PUZZLE#3]
Choisir 2 heuristiques à utiliser en plus du Manhattan Distance et noter :
       -   pourquoi ce choix
       -   particularite et fonctionnement de chaque heuristique
  afin de savoir l'expliquer pour la correction finale.

**Comment by Liliaze** [comment]
Pour le A* je propose d'utiliser les heuristics qu'utilise tristant pennmann sur son site : http://tristanpenman.com/demos/n-puzzle/# elles sont bien expliqués et cohérentes. On peux utiliser les mêmes pour le greedy search.

**Comment by Liliaze** [comment]
Pour l'instant on a mis les heuristiques les plus simples. C'est suffisant pour le sujet, est-ce-qu'elles te conviennent ou on en ajoute ? Faudrait ajouter un petit descriptif peut-être...

**Comment by mdugot42** [comment]
J'ai ajouté le linear-conflict qui reprend le manhattan distance en l'optimisant un peu. On peut ajouter un descriptif si tu penses que c'est utile.

**Comment by Liliaze** [comment]
Perfect !
